const clockPresets = [
  {
    name: "Classic",
    bodyColor: "#8EB672",
    dialColor: "#ffffff",
    handsColor: "#E54D4C",
    dialDesign: "Full Markers",
    handsDesign: "Chopsticks",
  },
  {
    name: "Retro",
    bodyColor: "#F4A261",
    dialColor: "#2A9D8F",
    handsColor: "#E76F51",
    dialDesign: "Full Markers",
    handsDesign: "Bold",
  },
  {
    name: "Monochrome",
    bodyColor: "#888888",
    dialColor: "#CCCCCC",
    handsColor: "#444444",
    dialDesign: "Full Markers",
    handsDesign: "Chopsticks",
  },
  {
    name: "Earth Tones",
    bodyColor: "#A0522D",
    dialColor: "#DEB887",
    handsColor: "#556B2F",
    dialDesign: "Full Markers",
    handsDesign: "Chopsticks",
  },
  {
    name: "Ocean",
    bodyColor: "#0077BE",
    dialColor: "#00A9E0",
    handsColor: "#003F5C",
    dialDesign: "Full Markers",
    handsDesign: "Chopsticks",
  },
  {
    name: "Sunset",
    bodyColor: "#FF4500",
    dialColor: "#FFD700",
    handsColor: "#8B0000",
    dialDesign: "Smile",
    handsDesign: "Chopsticks",
  },
  {
    name: "New York",
    bodyColor: "#1C1C1C",
    dialColor: "#F0E68C",
    handsColor: "#B22222",
    dialDesign: "Full Markers",
    handsDesign: "Chopsticks",
  },
];

export default clockPresets;
